fastlane_version "1.100.0"

default_platform :ios

lane :lint do
  swiftlint
end

lane :test_local do
  scan(scheme: "ProductClient", clean: false, code_coverage: true, skip_slack: true)
  xcov(scheme: "ProductClient", skip_slack: true)
  scan(scheme: "ProductClientContractTests", clean: false, skip_slack: true)
end

lane :test do
  ensure_git_status_clean
  scan(scheme: "ProductClient", clean: true, code_coverage: true, skip_slack: true)
  xcov(scheme: "ProductClient", skip_slack: true)
end

lane :contract_tests do
  ensure_git_status_clean
  scan(scheme: "ProductClientContractTests", clean: true, skip_slack: true)
end
